/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class CareTaker extends javax.swing.JFrame {

    /**
     * Creates new form CareTaker
     */
    public CareTaker() {
        initComponents();
        show_user();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        careTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("CareTaker");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 0, 150, 41));

        jLabel2.setBackground(new java.awt.Color(153, 255, 153));
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 41, 87, 25));

        jLabel3.setBackground(new java.awt.Color(153, 255, 153));
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("PhoneNumber");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 84, 87, 25));

        jLabel4.setBackground(new java.awt.Color(153, 255, 153));
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 121, 87, 25));

        jLabel5.setBackground(new java.awt.Color(153, 255, 153));
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 152, 87, 25));

        jLabel6.setBackground(new java.awt.Color(153, 255, 153));
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Salary");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 183, 87, 25));

        jLabel7.setBackground(new java.awt.Color(153, 255, 153));
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("National ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 226, 87, 25));

        jLabel8.setBackground(new java.awt.Color(153, 255, 153));
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Permanent Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 257, 125, 25));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 41, 136, 25));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 112, 136, 32));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 74, 136, 32));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 163, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 163, -1, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 188, 134, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 219, 93, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 257, 197, 80));

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 474, -1, -1));

        jButton2.setText("update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 474, -1, -1));

        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 474, -1, -1));

        careTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PHONENUMBER", "Address", "Gender", "salary", "national ID", "FIX address"
            }
        ));
        careTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                careTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(careTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 56, 609, 272));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    public ArrayList<CareTakers> workerlist(){
     ArrayList<CareTakers> workerlist = new ArrayList<>();
     try{
            Connection con=MyConnection.getConnection();
            String query1 = "SELECT * FROM caretaker";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            CareTakers ct;
            while(rs.next()){
                ct = new CareTakers(rs.getString("name"),rs.getInt("phoneno"),rs.getString("address"),rs.getString("gender"),rs.getInt("salary"),rs.getInt("nationalid"),rs.getString("permanentaddress"));
                workerlist.add(ct);
            }
     }catch(Exception e){        
     }
        return workerlist;}
     public void show_user(){
                ArrayList<CareTakers> list = workerlist();
                DefaultTableModel model = (DefaultTableModel)careTable.getModel();
                Object[] row = new Object[7];
                for (int i=0;i<list.size();i++){
         row[0]=list.get(i).getName();
         row[1]=list.get(i).getPhoneno();
         row[2]=list.get(i).getAddress();
         row[3]=list.get(i).getGender();
         row[4]=list.get(i).getSalary();
         row[5]=list.get(i).getNationalid();
         row[6]=list.get(i).getPermanentaddress();
        // row[7]=list.get(i).getDate();
         model.addRow(row);
     }
            }
       
         
     
    
    public boolean verify(){
        if(jTextField1.getText().equals("") || jTextField2.getText().equals("") ||jTextField3.getText().equals("") || jTextField4.getText().equals("")||jTextField5.getText().equals("") ||jTextArea1.getText().equals("") || buttonGroup1.getSelection()== null)
            return false;
        else
            return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:     
       // if(verify()){
       if(true){ String name=jTextField1.getText();
       
        int phoneno =Integer.parseInt(jTextField3.getText());
        String paddress=jTextArea1.getText();
        String taddress=jTextField2.getText();
        int salary=Integer.parseInt(jTextField4.getText());
        
        int nationalid=Integer.parseInt(jTextField5.getText());

        String gender;
        
        if(jRadioButton2.isSelected()){
            gender="Female";
        }else{
            gender="Male";
        }
       
       // SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       
        //String date = sdf.format(jTimeChooser1.getDate());
       
        CareTakerData ctd= new CareTakerData();
        
        try {
            ctd.Add(name, phoneno,  paddress,gender, salary, nationalid,taddress);
              DefaultTableModel model = (DefaultTableModel)careTable.getModel();
              model.setRowCount(0);
              show_user();
        } catch(SQLException e){
            System.err.print(e);
            JOptionPane.showMessageDialog(null,"ID already exists");
            
        }
        
        }
        else{
            JOptionPane.showMessageDialog(null,"One or more field is empty");
        }
       //it doubles the entry
  //show_user();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(true){ String name=jTextField1.getText();
       
        int phoneno =Integer.parseInt(jTextField3.getText());
        String paddress=jTextArea1.getText();
        String taddress=jTextField2.getText();
        int salary=Integer.parseInt(jTextField4.getText());
        
        int nationalid=Integer.parseInt(jTextField5.getText());

        String gender;
        
        if(jRadioButton2.isSelected()){
            gender="Female";
        }else{
            gender="Male";
        }
       
        CareTakerData ctd= new CareTakerData();
        
        try {
            ctd.Update(name, phoneno,  paddress,gender, salary, nationalid,taddress);
            DefaultTableModel model = (DefaultTableModel)careTable.getModel();
              model.setRowCount(0);
              show_user();
        } catch(SQLException e){
            System.err.print(e);
            
            
        }
        
        }
        else{
            JOptionPane.showMessageDialog(null,"One or more field is empty");
        }

    }//GEN-LAST:event_jButton2ActionPerformed
//delete button
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(true){
              int nationalid=Integer.parseInt(jTextField5.getText());
        CareTakerData ctd= new CareTakerData();
        
        try {
            ctd.Delete( nationalid);
            DefaultTableModel model = (DefaultTableModel)careTable.getModel();
              model.setRowCount(0);
              show_user();
        } catch(SQLException e){
            System.err.print(e);
            
        }
        
        }
        else{
            JOptionPane.showMessageDialog(null,"One or more field is empty");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void careTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_careTableMouseClicked
        // TODO add your handling code here:
        int i = careTable.getSelectedRow();
        TableModel model = careTable.getModel();
        jTextField1.setText(model.getValueAt(i,0).toString());
        jTextField3.setText(model.getValueAt(i,1).toString());
        jTextField2.setText(model.getValueAt(i,2).toString());
       String gender = model.getValueAt(i,3).toString();
       if(gender.equals("Male")){
           jRadioButton1.setSelected(true);}
       else{
           jRadioButton2.setSelected(true);
       }
       jTextField4.setText(model.getValueAt(i,4).toString());
       jTextField5.setText(model.getValueAt(i,5).toString());
       jTextArea1.setText(model.getValueAt(i,6).toString());
    }//GEN-LAST:event_careTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CareTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CareTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CareTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CareTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CareTaker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTable careTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
